package evidence

import (
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"testing"

	"github.com/seebom-labs/vexviper/internal/source"
)

func mustGraph(t *testing.T, dir string, rel string) *depGraph {
	t.Helper()
	read := func(p string) []byte {
		b, err := readRel(dir, p)
		if err != nil {
			return nil
		}
		return b
	}
	data := read(rel)
	if data == nil {
		t.Fatalf("missing %s", rel)
	}
	g := loadGraph(rel, data, read)
	if g == nil {
		t.Fatalf("no graph for %s", rel)
	}
	return g
}

func TestPackageLockV3(t *testing.T) {
	dir := writeTree(t, map[string]string{
		"package-lock.json": `{
  "lockfileVersion": 3,
  "packages": {
    "": {"dependencies": {"express": "^4"}, "devDependencies": {"jest": "^29"}},
    "node_modules/express": {"version": "4.18.2", "dependencies": {"qs": "6.11.0", "body-parser": "1.20.1"}},
    "node_modules/body-parser": {"version": "1.20.1", "dependencies": {"qs": "6.11.0"}},
    "node_modules/qs": {"version": "6.11.0"},
    "node_modules/jest": {"version": "29.0.0", "dev": true, "dependencies": {"minimist": "1.2.0"}},
    "node_modules/minimist": {"version": "1.2.0", "dev": true},
    "node_modules/jest/node_modules/minimist": {"version": "1.2.5", "dev": true}
  }
}`,
	})
	g := mustGraph(t, dir, "package-lock.json")
	if !g.HasEdges || !g.DevFlags || !g.RootKnown || !g.DevSplit {
		t.Fatalf("flags: %+v", g)
	}
	if got := g.dependents("qs"); !reflect.DeepEqual(got, []string{"body-parser", "express"}) {
		t.Fatalf("dependents(qs) = %v", got)
	}
	if dev, known := g.devOnly("minimist"); !dev || !known {
		t.Fatalf("minimist dev=%v known=%v", dev, known)
	}
	if dev, known := g.devOnly("qs"); dev || !known {
		t.Fatalf("qs dev=%v known=%v", dev, known)
	}
	paths := g.pathsTo("qs", 3)
	if len(paths) != 1 || !reflect.DeepEqual(paths[0], []string{"express", "qs"}) {
		t.Fatalf("paths = %v", paths)
	}
	if got := g.dependents("express"); len(got) != 0 {
		t.Fatalf("express dependents = %v", got)
	}
}

func TestPackageLockV1(t *testing.T) {
	dir := writeTree(t, map[string]string{
		"package.json": `{"dependencies":{"a":"1"},"devDependencies":{"mocha":"1"}}`,
		"package-lock.json": `{"lockfileVersion": 1, "dependencies": {
  "a": {"version": "1.0.0", "requires": {"b": "1"}, "dependencies": {"b": {"version": "1.0.0"}}},
  "mocha": {"version": "1.0.0", "dev": true, "requires": {"debug": "1"}},
  "debug": {"version": "1.0.0", "dev": true}
}}`,
	})
	g := mustGraph(t, dir, "package-lock.json")
	if dev, known := g.devOnly("debug"); !dev || !known {
		t.Fatalf("debug dev=%v known=%v", dev, known)
	}
	if got := g.dependents("b"); !reflect.DeepEqual(got, []string{"a"}) {
		t.Fatalf("dependents(b) = %v", got)
	}
	if !g.RootKnown || !reflect.DeepEqual(g.Root, []string{"a"}) || !reflect.DeepEqual(g.RootDev, []string{"mocha"}) {
		t.Fatalf("root = %v dev = %v", g.Root, g.RootDev)
	}
}

func TestYarnLock(t *testing.T) {
	dir := writeTree(t, map[string]string{
		"package.json": `{"dependencies":{"react":"18"},"devDependencies":{"eslint":"8"}}`,
		"yarn.lock": `# THIS IS AN AUTOGENERATED FILE.
# yarn lockfile v1

"@babel/code-frame@^7.0.0":
  version "7.0.0"
  dependencies:
    "@babel/highlight" "^7.0.0"

"@babel/highlight@^7.0.0":
  version "7.0.0"

eslint@8, "eslint@^8.0.0":
  version "8.0.0"
  dependencies:
    "@babel/code-frame" "^7.0.0"
    debug "^4"

debug@^4:
  version "4.3.4"

react@18:
  version "18.2.0"
  dependencies:
    loose-envify "^1.1.0"

loose-envify@^1.1.0:
  version "1.4.0"
`,
	})
	g := mustGraph(t, dir, "yarn.lock")
	if got := g.dependents("@babel/highlight"); !reflect.DeepEqual(got, []string{"@babel/code-frame"}) {
		t.Fatalf("dependents = %v", got)
	}
	if dev, known := g.devOnly("@babel/highlight"); !dev || !known {
		t.Fatalf("highlight dev=%v known=%v", dev, known)
	}
	if dev, known := g.devOnly("loose-envify"); dev || !known {
		t.Fatalf("loose-envify dev=%v known=%v", dev, known)
	}
	if p := g.pathsTo("@babel/highlight", 2); len(p) != 1 || len(p[0]) != 3 {
		t.Fatalf("paths = %v", p)
	}
}

func TestYarnBerry(t *testing.T) {
	dir := writeTree(t, map[string]string{
		"package.json": `{"dependencies":{"left-pad":"1"},"workspaces":["packages/*"]}`,
		"yarn.lock": `__metadata:
  version: 6

"left-pad@npm:1":
  version: 1.3.0
  resolution: "left-pad@npm:1.3.0"
  dependencies:
    "@scope/dep": "npm:^1"
    other: "npm:^2"

"@scope/dep@npm:^1":
  version: 1.0.0
`,
	})
	g := mustGraph(t, dir, "yarn.lock")
	if got := g.dependents("@scope/dep"); !reflect.DeepEqual(got, []string{"left-pad"}) {
		t.Fatalf("dependents = %v", got)
	}
	if g.DevSplit {
		t.Fatal("workspaces must disable the root dev split")
	}
	if _, known := g.devOnly("@scope/dep"); known {
		t.Fatal("dev-only must be unknown without a dev split")
	}
}

func TestPnpmLock(t *testing.T) {
	dir := writeTree(t, map[string]string{
		"pnpm-lock.yaml": `lockfileVersion: '9.0'
importers:
  .:
    dependencies:
      axios:
        specifier: ^1
        version: 1.6.0
    devDependencies:
      vitest:
        specifier: ^1
        version: 1.0.0
packages:
  axios@1.6.0:
    resolution: {integrity: sha512-x}
  follow-redirects@1.15.0:
    resolution: {integrity: sha512-y}
  vitest@1.0.0:
    resolution: {integrity: sha512-z}
  tinypool@0.8.0:
    resolution: {integrity: sha512-w}
snapshots:
  axios@1.6.0:
    dependencies:
      follow-redirects: 1.15.0
  follow-redirects@1.15.0: {}
  vitest@1.0.0:
    dependencies:
      tinypool: 0.8.0
  tinypool@0.8.0: {}
`,
	})
	g := mustGraph(t, dir, "pnpm-lock.yaml")
	if dev, known := g.devOnly("tinypool"); !dev || !known {
		t.Fatalf("tinypool dev=%v known=%v", dev, known)
	}
	if dev, known := g.devOnly("follow-redirects"); dev || !known {
		t.Fatalf("follow-redirects dev=%v known=%v", dev, known)
	}
	if got := g.dependents("follow-redirects"); !reflect.DeepEqual(got, []string{"axios"}) {
		t.Fatalf("dependents = %v", got)
	}
}

func TestPnpmKeyName(t *testing.T) {
	cases := map[string]string{
		"/lodash/4.17.21":               "lodash",
		"/@babel/core/7.0.0":            "@babel/core",
		"/lodash@4.17.21":               "lodash",
		"/@babel/core@7.0.0(peer@1)":    "@babel/core",
		"lodash@4.17.21":                "lodash",
		"@babel/core@7.0.0":             "@babel/core",
		"vitest@1.0.0(@types/node@20)":  "vitest",
		"/@scope/name/1.0.0_peer@1.0.0": "@scope/name",
	}
	for in, want := range cases {
		if got := pnpmKeyName(in); got != want {
			t.Errorf("pnpmKeyName(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestCargoLock(t *testing.T) {
	dir := writeTree(t, map[string]string{
		"Cargo.toml": "[package]\nname = \"demo\"\n\n[dependencies]\nsmallvec = \"1\"\nserde = \"1\"\n\n[dev-dependencies]\nproptest = \"1\"\n",
		"Cargo.lock": `# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "demo"
version = "0.1.0"
dependencies = [
 "proptest",
 "serde",
 "smallvec",
]

[[package]]
name = "proptest"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "rand_core 0.6.4",
]

[[package]]
name = "rand_core"
version = "0.6.4"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "serde"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = ["serde_derive"]

[[package]]
name = "serde_derive"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "smallvec"
version = "1.6.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
`,
	})
	g := mustGraph(t, dir, "Cargo.lock")
	if g.has("demo") {
		t.Fatal("workspace member must not be a node")
	}
	if got := g.dependents("smallvec"); len(got) != 0 {
		t.Fatalf("smallvec dependents = %v", got)
	}
	if got := g.dependents("rand_core"); !reflect.DeepEqual(got, []string{"proptest"}) {
		t.Fatalf("rand_core dependents = %v", got)
	}
	if got := g.dependents("serde_derive"); !reflect.DeepEqual(got, []string{"serde"}) {
		t.Fatalf("serde_derive dependents = %v (single-line array)", got)
	}
	if !g.DevSplit || !reflect.DeepEqual(g.RootDev, []string{"proptest"}) {
		t.Fatalf("dev split = %v, rootDev = %v", g.DevSplit, g.RootDev)
	}
	if dev, known := g.devOnly("rand_core"); !dev || !known {
		t.Fatalf("rand_core dev=%v known=%v", dev, known)
	}
	if dev, known := g.devOnly("smallvec"); dev || !known {
		t.Fatalf("smallvec dev=%v known=%v", dev, known)
	}
}

func TestCargoWorkspaceNoDevSplit(t *testing.T) {
	dir := writeTree(t, map[string]string{
		"Cargo.toml": "[workspace]\nmembers = [\"a\", \"b\"]\n",
		"Cargo.lock": "[[package]]\nname = \"a\"\nversion = \"0.1.0\"\ndependencies = [\"x\"]\n\n[[package]]\nname = \"x\"\nversion = \"1.0.0\"\nsource = \"registry+x\"\n",
	})
	g := mustGraph(t, dir, "Cargo.lock")
	if g.DevSplit {
		t.Fatal("workspace must not claim a dev split")
	}
	if !g.RootKnown || !g.isRoot("x") {
		t.Fatalf("root = %v", g.Root)
	}
}

func TestPoetryLock(t *testing.T) {
	dir := writeTree(t, map[string]string{
		"pyproject.toml": "[tool.poetry.dependencies]\npython = \"^3.11\"\nrequests = \"^2\"\n\n[tool.poetry.group.dev.dependencies]\npytest = \"^8\"\n",
		"poetry.lock": `[[package]]
name = "requests"
version = "2.31.0"
groups = ["main"]

[package.dependencies]
urllib3 = ">=1.21.1,<3"
charset-normalizer = {version = ">=2", optional = false}

[[package]]
name = "urllib3"
version = "2.1.0"
groups = ["main"]

[[package]]
name = "charset-normalizer"
version = "3.0.0"
groups = ["main"]

[[package]]
name = "pytest"
version = "8.0.0"
groups = ["dev"]

[package.dependencies]
pluggy = ">=1.3"

[[package]]
name = "pluggy"
version = "1.4.0"
groups = ["dev"]
`,
	})
	g := mustGraph(t, dir, "poetry.lock")
	if !g.DevFlags {
		t.Fatal("poetry groups must be authoritative")
	}
	if dev, known := g.devOnly("Pluggy"); !dev || !known {
		t.Fatalf("pluggy dev=%v known=%v", dev, known)
	}
	if got := g.dependents("Charset_Normalizer"); !reflect.DeepEqual(got, []string{"requests"}) {
		t.Fatalf("dependents = %v", got)
	}
	if p := g.pathsTo("urllib3", 1); len(p) != 1 || !reflect.DeepEqual(p[0], []string{"requests", "urllib3"}) {
		t.Fatalf("paths = %v", p)
	}
}

func TestPoetryLockCategory(t *testing.T) {
	dir := writeTree(t, map[string]string{
		"poetry.lock": "[[package]]\nname = \"black\"\nversion = \"24.0.0\"\ncategory = \"dev\"\n\n[[package]]\nname = \"click\"\nversion = \"8.0.0\"\ncategory = \"main\"\n",
	})
	g := mustGraph(t, dir, "poetry.lock")
	if dev, known := g.devOnly("black"); !dev || !known {
		t.Fatalf("black dev=%v known=%v", dev, known)
	}
	if dev, _ := g.devOnly("click"); dev {
		t.Fatal("click is main")
	}
}

func TestUvLock(t *testing.T) {
	dir := writeTree(t, map[string]string{
		"uv.lock": `version = 1

[[package]]
name = "demo"
version = "0.1.0"
source = { editable = "." }
dependencies = [
    { name = "httpx" },
]

[package.dev-dependencies]
dev = [
    { name = "pytest" },
]

[[package]]
name = "httpx"
version = "0.27.0"
source = { registry = "https://pypi.org/simple" }
dependencies = [{ name = "httpcore" }, { name = "idna" }]

[[package]]
name = "httpcore"
version = "1.0.0"
source = { registry = "https://pypi.org/simple" }

[[package]]
name = "idna"
version = "3.6"
source = { registry = "https://pypi.org/simple" }

[[package]]
name = "pytest"
version = "8.0.0"
source = { registry = "https://pypi.org/simple" }
dependencies = [
    { name = "pluggy" },
]

[[package]]
name = "pluggy"
version = "1.4.0"
source = { registry = "https://pypi.org/simple" }
`,
	})
	g := mustGraph(t, dir, "uv.lock")
	if !g.RootKnown || !g.DevSplit || !reflect.DeepEqual(g.Root, []string{"httpx"}) || !reflect.DeepEqual(g.RootDev, []string{"pytest"}) {
		t.Fatalf("root = %v dev = %v", g.Root, g.RootDev)
	}
	if dev, known := g.devOnly("pluggy"); !dev || !known {
		t.Fatalf("pluggy dev=%v known=%v", dev, known)
	}
	if got := g.dependents("idna"); !reflect.DeepEqual(got, []string{"httpx"}) {
		t.Fatalf("dependents(idna) = %v (single-line array)", got)
	}
}

func TestPipfileLock(t *testing.T) {
	dir := writeTree(t, map[string]string{
		"Pipfile":      "[packages]\nflask = \"*\"\n\n[dev-packages]\npytest = \"*\"\n",
		"Pipfile.lock": `{"default": {"flask": {"version": "==3.0.0"}, "werkzeug": {"version": "==3.0.0"}}, "develop": {"pytest": {"version": "==8"}, "werkzeug": {"version": "==3.0.0"}, "iniconfig": {"version": "==2"}}}`,
	})
	g := mustGraph(t, dir, "Pipfile.lock")
	if g.HasEdges {
		t.Fatal("Pipfile.lock has no edges")
	}
	if dev, known := g.devOnly("iniconfig"); !dev || !known {
		t.Fatalf("iniconfig dev=%v known=%v", dev, known)
	}
	if dev, _ := g.devOnly("werkzeug"); dev {
		t.Fatal("werkzeug is in default too")
	}
	if !g.isRoot("pytest") || !g.isRoot("flask") {
		t.Fatalf("root = %v dev = %v", g.Root, g.RootDev)
	}
}

func TestGemfileLock(t *testing.T) {
	dir := writeTree(t, map[string]string{
		"Gemfile": "source 'https://rubygems.org'\ngem 'rack'\ngroup :development, :test do\n  gem 'rspec'\nend\ngem 'pry', group: :development\n",
		"Gemfile.lock": `GEM
  remote: https://rubygems.org/
  specs:
    coderay (1.1.3)
    diff-lcs (1.5.0)
    method_source (1.0.0)
    pry (0.14.2)
      coderay (~> 1.1)
      method_source (~> 1.0)
    rack (3.0.8)
    rspec (3.12.0)
      rspec-core (~> 3.12.0)
    rspec-core (3.12.0)
      rspec-support (~> 3.12.0)
    rspec-support (3.12.0)

PLATFORMS
  ruby

DEPENDENCIES
  pry
  rack
  rspec

BUNDLED WITH
   2.4.10
`,
	})
	g := mustGraph(t, dir, "Gemfile.lock")
	if !reflect.DeepEqual(g.Root, []string{"rack"}) {
		t.Fatalf("root = %v, dev = %v", g.Root, g.RootDev)
	}
	sort.Strings(g.RootDev)
	if !reflect.DeepEqual(g.RootDev, []string{"pry", "rspec"}) {
		t.Fatalf("rootDev = %v", g.RootDev)
	}
	if dev, known := g.devOnly("rspec-support"); !dev || !known {
		t.Fatalf("rspec-support dev=%v known=%v", dev, known)
	}
	if got := g.dependents("coderay"); !reflect.DeepEqual(got, []string{"pry"}) {
		t.Fatalf("dependents = %v", got)
	}
	if p := g.pathsTo("rspec-support", 1); len(p) != 1 || len(p[0]) != 3 {
		t.Fatalf("paths = %v", p)
	}
}

func TestComposerLock(t *testing.T) {
	dir := writeTree(t, map[string]string{
		"composer.json": `{"require":{"php":">=8.1","monolog/monolog":"^3"},"require-dev":{"phpunit/phpunit":"^10"}}`,
		"composer.lock": `{"packages":[
  {"name":"monolog/monolog","require":{"php":">=8.1","psr/log":"^2 || ^3"},"autoload":{"psr-4":{"Monolog\\":"src/Monolog"}}},
  {"name":"psr/log","require":{"php":">=8.0"},"autoload":{"psr-4":{"Psr\\Log\\":"src"}}}
 ],"packages-dev":[
  {"name":"phpunit/phpunit","require":{"sebastian/diff":"^5"},"autoload":{"psr-4":{"PHPUnit\\":"src/"}}},
  {"name":"sebastian/diff","require":{"php":">=8.1"},"autoload":{"psr-4":{"SebastianBergmann\\Diff\\":"src/"}}}
 ]}`,
	})
	g := mustGraph(t, dir, "composer.lock")
	if dev, known := g.devOnly("sebastian/diff"); !dev || !known {
		t.Fatalf("sebastian/diff dev=%v known=%v", dev, known)
	}
	if got := g.dependents("psr/log"); !reflect.DeepEqual(got, []string{"monolog/monolog"}) {
		t.Fatalf("dependents = %v", got)
	}
	if ns := g.Namespaces["psr/log"]; !reflect.DeepEqual(ns, []string{`Psr\Log`}) {
		t.Fatalf("namespaces = %v", ns)
	}
	if !reflect.DeepEqual(g.Root, []string{"monolog/monolog"}) || !reflect.DeepEqual(g.RootDev, []string{"phpunit/phpunit"}) {
		t.Fatalf("root = %v dev = %v", g.Root, g.RootDev)
	}
}

func TestNugetLock(t *testing.T) {
	dir := writeTree(t, map[string]string{
		"packages.lock.json": `{"version": 1, "dependencies": {"net8.0": {
  "Newtonsoft.Json": {"type": "Direct", "requested": "[13.0.1, )", "resolved": "13.0.1"},
  "Serilog.Sinks.File": {"type": "Direct", "resolved": "5.0.0", "dependencies": {"Serilog": "2.10.0"}},
  "Serilog": {"type": "Transitive", "resolved": "2.10.0"},
  "MyLib": {"type": "Project", "dependencies": {"Dapper": "2.0.0"}},
  "Dapper": {"type": "Transitive", "resolved": "2.0.0"}
}}}`,
	})
	g := mustGraph(t, dir, "packages.lock.json")
	if !g.isRoot("newtonsoft.json") || !g.isRoot("Dapper") {
		t.Fatalf("root = %v", g.Root)
	}
	if got := g.dependents("serilog"); !reflect.DeepEqual(got, []string{"serilog.sinks.file"}) {
		t.Fatalf("dependents = %v", got)
	}
	if _, known := g.devOnly("serilog"); known {
		t.Fatal("nuget lockfile has no dev split")
	}
}

func TestPubspecLock(t *testing.T) {
	dir := writeTree(t, map[string]string{
		"pubspec.lock": "packages:\n  http:\n    dependency: \"direct main\"\n    version: \"1.2.0\"\n  test:\n    dependency: \"direct dev\"\n    version: \"1.25.0\"\n  meta:\n    dependency: transitive\n    version: \"1.11.0\"\n",
	})
	g := mustGraph(t, dir, "pubspec.lock")
	if !reflect.DeepEqual(g.Root, []string{"http"}) || !reflect.DeepEqual(g.RootDev, []string{"test"}) {
		t.Fatalf("root = %v dev = %v", g.Root, g.RootDev)
	}
	if !g.has("meta") || g.HasEdges {
		t.Fatalf("meta present=%v edges=%v", g.has("meta"), g.HasEdges)
	}
}

func TestGradleLockfile(t *testing.T) {
	dir := writeTree(t, map[string]string{
		"gradle.lockfile": "# This is a Gradle generated file for dependency locking.\ncom.fasterxml.jackson.core:jackson-databind:2.15.0=compileClasspath,runtimeClasspath,testRuntimeClasspath\norg.junit.jupiter:junit-jupiter:5.10.0=testCompileClasspath,testRuntimeClasspath\nempty=annotationProcessor\n",
	})
	g := mustGraph(t, dir, "gradle.lockfile")
	if dev, known := g.devOnly("org.junit.jupiter:junit-jupiter"); !dev || !known {
		t.Fatalf("junit dev=%v known=%v", dev, known)
	}
	if dev, _ := g.devOnly("com.fasterxml.jackson.core:jackson-databind"); dev {
		t.Fatal("jackson is runtime")
	}
	// Only test configurations locked: nothing is dev-only.
	dir = writeTree(t, map[string]string{"gradle.lockfile": "org.junit.jupiter:junit-jupiter:5.10.0=testRuntimeClasspath\n"})
	g = mustGraph(t, dir, "gradle.lockfile")
	if _, known := g.devOnly("org.junit.jupiter:junit-jupiter"); known {
		t.Fatal("test-only lockfile must not claim dev-only")
	}
}

func TestNpmSpecName(t *testing.T) {
	cases := map[string]string{"lodash@^4": "lodash", "@babel/core@^7": "@babel/core", "@babel/core@npm:^7": "@babel/core", "__metadata": "", "": ""}
	for in, want := range cases {
		if got := npmSpecName(in); got != want {
			t.Errorf("npmSpecName(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestJavaPackageCandidates(t *testing.T) {
	cases := map[string][]string{
		"org.apache.commons/commons-text":              {"org.apache.commons.commons.text", "org.apache.commons.text", "org.apache.commons"},
		"com.fasterxml.jackson.core/jackson-databind":  {"com.fasterxml.jackson.core.jackson.databind", "com.fasterxml.jackson.databind"},
		"org.springframework/spring-web":               {"org.springframework.spring.web", "org.springframework.web", "org.springframework"},
		"com.google.guava/guava":                       {"com.google.guava.guava", "com.google.guava"},
		"org.apache.logging.log4j/log4j-core":          {"org.apache.logging.log4j.log4j.core", "org.apache.logging.log4j.core", "org.apache.logging.log4j"},
		"io.netty/netty-codec-http":                    {"io.netty.netty.codec.http", "io.netty.codec.http", "io.netty"},
		"ch.qos.logback/logback-classic":               {"ch.qos.logback.logback.classic", "ch.qos.logback.classic", "ch.qos.logback"},
		"org.yaml/snakeyaml":                           {"org.yaml.snakeyaml"},
		"com.squareup.okhttp3/okhttp":                  {"com.squareup.okhttp3.okhttp"},
		"org.eclipse.jetty/jetty-server":               {"org.eclipse.jetty.jetty.server", "org.eclipse.jetty.server", "org.eclipse.jetty"},
		"org.apache.tomcat.embed/tomcat-embed-core":    {"org.apache.tomcat.embed.tomcat.embed.core", "org.apache.tomcat.embed.core"},
		"org.bouncycastle/bcprov-jdk18on":              {"org.bouncycastle.bcprov.jdk18on"},
		"com.fasterxml.jackson.dataformat/jackson-xml": {"com.fasterxml.jackson.dataformat.jackson.xml", "com.fasterxml.jackson.xml"},
	}
	for in, want := range cases {
		g, a, _ := splitMaven(in)
		if got := javaPackageCandidates(g, a); !reflect.DeepEqual(got, want) {
			t.Errorf("javaPackageCandidates(%q) = %v, want %v", in, got, want)
		}
	}
}

func splitMaven(name string) (string, string, bool) {
	g, a, ok := cut(name, "/")
	return g, a, ok
}

func cut(s, sep string) (string, string, bool) {
	for i := 0; i+len(sep) <= len(s); i++ {
		if s[i:i+len(sep)] == sep {
			return s[:i], s[i+len(sep):], true
		}
	}
	return s, "", false
}

// ---- strong rules through the scan ----

func strongKinds(items []Item) []string {
	var out []string
	for _, it := range items {
		if it.Strong {
			out = append(out, string(it.Kind))
		}
	}
	sort.Strings(out)
	return out
}

func TestStrongDevDependencyFromLockfile(t *testing.T) {
	c := &Collector{}
	dir := writeTree(t, map[string]string{
		"package.json": `{"dependencies":{"express":"^4"},"devDependencies":{"jest":"^29"}}`,
		"package-lock.json": `{"lockfileVersion": 3, "packages": {
  "": {"dependencies": {"express": "^4"}, "devDependencies": {"jest": "^29"}},
  "node_modules/express": {"version": "4.18.2", "dependencies": {"qs": "6.11.0"}},
  "node_modules/qs": {"version": "6.11.0"},
  "node_modules/jest": {"version": "29.0.0", "dev": true, "dependencies": {"minimist": "1.2.0"}},
  "node_modules/minimist": {"version": "1.2.0", "dev": true}
}}`,
		"src/app.js": "const express = require('express');\n",
	})
	t.Run("transitive dev-only is strong", func(t *testing.T) {
		items := c.ecosystemEvidence(dir, source.Finding{PURL: "pkg:npm/minimist@1.2.0"})
		if got := strongKinds(items); !reflect.DeepEqual(got, []string{string(KindDevDependency)}) {
			t.Fatalf("strong = %v, all = %v", got, kindsOf(items))
		}
		if !hasKind(items, KindTransitive) || !hasKind(items, KindDependencyPath) {
			t.Fatalf("kinds = %v", kindsOf(items))
		}
	})
	t.Run("runtime transitive is not strong and carries a path", func(t *testing.T) {
		items := c.ecosystemEvidence(dir, source.Finding{PURL: "pkg:npm/qs@6.11.0"})
		if got := strongKinds(items); len(got) != 0 {
			t.Fatalf("strong = %v", got)
		}
		for _, it := range items {
			if it.Kind == KindDependencyPath {
				if ps, _ := it.Details["paths"].([]string); len(ps) != 1 || ps[0] != "express → qs" {
					t.Fatalf("paths = %v", it.Details["paths"])
				}
				return
			}
		}
		t.Fatalf("no dependency_path: %v", kindsOf(items))
	})
	t.Run("manifest dev but lockfile runtime is not dev", func(t *testing.T) {
		dir := writeTree(t, map[string]string{
			"package.json": `{"dependencies":{"a":"1"},"devDependencies":{"qs":"6"}}`,
			"package-lock.json": `{"lockfileVersion": 3, "packages": {
  "": {"dependencies": {"a": "1"}, "devDependencies": {"qs": "6"}},
  "node_modules/a": {"version": "1.0.0", "dependencies": {"qs": "6.11.0"}},
  "node_modules/qs": {"version": "6.11.0"}
}}`,
		})
		items := c.ecosystemEvidence(dir, source.Finding{PURL: "pkg:npm/qs@6.11.0"})
		if hasKind(items, KindDevDependency) {
			t.Fatalf("qs is in the runtime closure: %v", kindsOf(items))
		}
	})
}

func TestStrongImportNotFound(t *testing.T) {
	c := &Collector{}
	lock := `{"lockfileVersion": 3, "packages": {
  "": {"dependencies": {"left-pad": "1", "express": "4"}},
  "node_modules/left-pad": {"version": "1.3.0"},
  "node_modules/express": {"version": "4.18.2", "dependencies": {"qs": "6"}},
  "node_modules/qs": {"version": "6.11.0"}
}}`
	base := map[string]string{
		"package.json":      `{"dependencies":{"left-pad":"1","express":"4"},"scripts":{"start":"node src/app.js"}}`,
		"package-lock.json": lock,
		"src/app.js":        "const express = require('express');\n",
		"test/pad.test.js":  "const pad = require('left-pad');\n",
	}
	t.Run("direct, sole consumer, not imported → strong", func(t *testing.T) {
		items := c.ecosystemEvidence(writeTree(t, base), source.Finding{PURL: "pkg:npm/left-pad@1.3.0"})
		if got := strongKinds(items); !reflect.DeepEqual(got, []string{string(KindImportNotFound)}) {
			t.Fatalf("strong = %v, all = %v", got, kindsOf(items))
		}
	})
	t.Run("transitive with dependents is not strong", func(t *testing.T) {
		items := c.ecosystemEvidence(writeTree(t, base), source.Finding{PURL: "pkg:npm/qs@6.11.0"})
		if got := strongKinds(items); len(got) != 0 {
			t.Fatalf("strong = %v", got)
		}
	})
	t.Run("BOMHort says transitive → not strong", func(t *testing.T) {
		items := c.ecosystemEvidence(writeTree(t, base), source.Finding{PURL: "pkg:npm/left-pad@1.3.0", DirectKnown: true, Direct: false})
		if got := strongKinds(items); len(got) != 0 {
			t.Fatalf("strong = %v", got)
		}
	})
	t.Run("used in npm scripts → not strong", func(t *testing.T) {
		files := map[string]string{}
		for k, v := range base {
			files[k] = v
		}
		files["package.json"] = `{"dependencies":{"left-pad":"1","express":"4"},"scripts":{"pad":"left-pad 5"}}`
		items := c.ecosystemEvidence(writeTree(t, files), source.Finding{PURL: "pkg:npm/left-pad@1.3.0"})
		if got := strongKinds(items); len(got) != 0 {
			t.Fatalf("strong = %v", got)
		}
	})
	t.Run("without lockfile → not strong", func(t *testing.T) {
		files := map[string]string{}
		for k, v := range base {
			files[k] = v
		}
		delete(files, "package-lock.json")
		items := c.ecosystemEvidence(writeTree(t, files), source.Finding{PURL: "pkg:npm/left-pad@1.3.0"})
		if got := strongKinds(items); len(got) != 0 {
			t.Fatalf("strong = %v", got)
		}
	})
	t.Run("no source files at all → not strong", func(t *testing.T) {
		files := map[string]string{"package.json": base["package.json"], "package-lock.json": lock}
		items := c.ecosystemEvidence(writeTree(t, files), source.Finding{PURL: "pkg:npm/left-pad@1.3.0"})
		if got := strongKinds(items); len(got) != 0 {
			t.Fatalf("strong = %v", got)
		}
	})
	t.Run("pypi never strong (import names inferred)", func(t *testing.T) {
		dir := writeTree(t, map[string]string{
			"pyproject.toml": "[project]\nname = \"demo\"\ndependencies = [\"httpx\"]\n",
			"uv.lock":        "[[package]]\nname = \"demo\"\nversion = \"0.1.0\"\nsource = { editable = \".\" }\ndependencies = [{ name = \"httpx\" }]\n\n[[package]]\nname = \"httpx\"\nversion = \"0.27.0\"\nsource = { registry = \"x\" }\n",
			"demo/main.py":   "import sys\n",
		})
		items := c.ecosystemEvidence(dir, source.Finding{PURL: "pkg:pypi/httpx@0.27.0"})
		if got := strongKinds(items); len(got) != 0 {
			t.Fatalf("strong = %v", got)
		}
		if !hasKind(items, KindImportNotFound) || !hasKind(items, KindDependencyPath) {
			t.Fatalf("kinds = %v", kindsOf(items))
		}
	})
}

func TestComposerNamespaceImportScan(t *testing.T) {
	c := &Collector{}
	files := map[string]string{
		"composer.json": `{"require":{"monolog/monolog":"^3","league/csv":"^9"}}`,
		"composer.lock": `{"packages":[
  {"name":"monolog/monolog","require":{"psr/log":"^3"},"autoload":{"psr-4":{"Monolog\\":"src/Monolog"}}},
  {"name":"psr/log","require":{},"autoload":{"psr-4":{"Psr\\Log\\":"src"}}},
  {"name":"league/csv","require":{},"autoload":{"psr-4":{"League\\Csv\\":"src"}}}
 ],"packages-dev":[]}`,
		"app/Log.php":       "<?php\nnamespace App;\nuse Monolog\\Logger;\nclass Log { function l() { return new \\Monolog\\Handler\\StreamHandler('x'); } }\n",
		"tests/CsvTest.php": "<?php\nuse League\\Csv\\Reader;\n",
	}
	dir := writeTree(t, files)
	items := c.ecosystemEvidence(dir, source.Finding{PURL: "pkg:composer/monolog/monolog@3.0.0"})
	if !hasKind(items, KindPackageImported) {
		t.Fatalf("monolog kinds = %v", kindsOf(items))
	}
	// league/csv: direct, nobody depends on it, only a test file uses it → strong.
	items = c.ecosystemEvidence(dir, source.Finding{PURL: "pkg:composer/league/csv@9.0.0"})
	if got := strongKinds(items); !reflect.DeepEqual(got, []string{string(KindImportNotFound)}) {
		t.Fatalf("league/csv strong = %v, all = %v", got, kindsOf(items))
	}
	// psr/log: transitive with a dependent → never strong.
	items = c.ecosystemEvidence(dir, source.Finding{PURL: "pkg:composer/psr/log@3.0.0"})
	if got := strongKinds(items); len(got) != 0 {
		t.Fatalf("psr/log strong = %v", got)
	}
	// Package without namespaces in the lockfile: no import claim at all.
	items = c.ecosystemEvidence(dir, source.Finding{PURL: "pkg:composer/unknown/pkg@1.0.0"})
	if hasKind(items, KindImportNotFound) || hasKind(items, KindPackageImported) {
		t.Fatalf("unknown/pkg kinds = %v", kindsOf(items))
	}
}

func TestNugetAndPubEcosystems(t *testing.T) {
	c := &Collector{}
	t.Run("nuget", func(t *testing.T) {
		dir := writeTree(t, map[string]string{
			"App/App.csproj":         "<Project><ItemGroup><PackageReference Include=\"Newtonsoft.Json\" Version=\"13.0.1\" /><PackageReference Include=\"StyleCop.Analyzers\" Version=\"1.1.118\" PrivateAssets=\"all\" /></ItemGroup></Project>",
			"App/packages.lock.json": `{"version":1,"dependencies":{"net8.0":{"Newtonsoft.Json":{"type":"Direct","resolved":"13.0.1"},"StyleCop.Analyzers":{"type":"Direct","resolved":"1.1.118"}}}}`,
			"App/Program.cs":         "using System;\nusing Newtonsoft.Json;\nclass P { static void Main() { JsonConvert.SerializeObject(1); } }\n",
		})
		items := c.ecosystemEvidence(dir, source.Finding{PURL: "pkg:nuget/Newtonsoft.Json@13.0.1"})
		if !hasKind(items, KindDirectDependency) || !hasKind(items, KindPackageImported) || hasKind(items, KindDevDependency) {
			t.Fatalf("newtonsoft kinds = %v", kindsOf(items))
		}
		items = c.ecosystemEvidence(dir, source.Finding{PURL: "pkg:nuget/stylecop.analyzers@1.1.118"})
		if !hasKind(items, KindDevDependency) || !hasKind(items, KindImportNotFound) {
			t.Fatalf("stylecop kinds = %v", kindsOf(items))
		}
		if got := strongKinds(items); len(got) != 0 {
			t.Fatalf("nuget import names are inferred, strong = %v", got)
		}
	})
	t.Run("pub", func(t *testing.T) {
		dir := writeTree(t, map[string]string{
			"pubspec.yaml": "name: demo\ndependencies:\n  http: ^1.2.0\ndev_dependencies:\n  test: ^1.25.0\n",
			"pubspec.lock": "packages:\n  http:\n    dependency: \"direct main\"\n    version: \"1.2.0\"\n  test:\n    dependency: \"direct dev\"\n    version: \"1.25.0\"\n",
			"lib/api.dart": "import 'package:http/http.dart' as http;\n",
		})
		items := c.ecosystemEvidence(dir, source.Finding{PURL: "pkg:pub/http@1.2.0"})
		if !hasKind(items, KindDirectDependency) || !hasKind(items, KindPackageImported) {
			t.Fatalf("http kinds = %v", kindsOf(items))
		}
		items = c.ecosystemEvidence(dir, source.Finding{PURL: "pkg:pub/test@1.25.0"})
		if !hasKind(items, KindDevDependency) || !hasKind(items, KindImportNotFound) {
			t.Fatalf("test kinds = %v", kindsOf(items))
		}
		if got := strongKinds(items); len(got) != 0 {
			t.Fatalf("pubspec.lock has no graph; strong = %v", got)
		}
	})
}

func TestMavenImportScanAndScopes(t *testing.T) {
	c := &Collector{}
	dir := writeTree(t, map[string]string{
		"pom.xml": `<project><dependencies>
  <dependency><groupId>com.fasterxml.jackson.core</groupId><artifactId>jackson-databind</artifactId><version>2.15.0</version></dependency>
  <dependency><groupId>org.junit.jupiter</groupId><artifactId>junit-jupiter</artifactId><scope>test</scope></dependency>
</dependencies></project>`,
		"src/main/java/App.java":     "package app;\nimport com.fasterxml.jackson.databind.ObjectMapper;\npublic class App {}\n",
		"src/test/java/AppTest.java": "import org.junit.jupiter.api.Test;\n",
	})
	items := c.ecosystemEvidence(dir, source.Finding{PURL: "pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.15.0"})
	if !hasKind(items, KindDirectDependency) || !hasKind(items, KindPackageImported) || hasKind(items, KindDevDependency) {
		t.Fatalf("jackson kinds = %v", kindsOf(items))
	}
	items = c.ecosystemEvidence(dir, source.Finding{PURL: "pkg:maven/org.junit.jupiter/junit-jupiter@5.10.0"})
	if !hasKind(items, KindDevDependency) || !hasKind(items, KindImportNotFound) {
		t.Fatalf("junit kinds = %v", kindsOf(items))
	}
	if got := strongKinds(items); len(got) != 0 {
		t.Fatalf("maven is never strong, got %v", got)
	}
}

func readRel(dir, rel string) ([]byte, error) {
	return os.ReadFile(filepath.Join(dir, rel))
}
